revoke all on public.companies from anon, authenticated, public;
revoke all on public.profiles from anon, authenticated, public;
revoke all on public.app_roles from anon, authenticated, public;
revoke all on public.tool_groups from anon, authenticated, public;
revoke all on public.tools from anon, authenticated, public;
revoke all on public.equipment_groups from anon, authenticated, public;
revoke all on public.equipments from anon, authenticated, public;
revoke all on public.equipment_custom_fields from anon, authenticated, public;
revoke all on public.equipment_custom_field_values from anon, authenticated, public;
revoke all on public.tool_custom_fields from anon, authenticated, public;
revoke all on public.tool_custom_field_values from anon, authenticated, public;
revoke all on public.employee_companies from anon, authenticated, public;
revoke all on public.employees from anon, authenticated, public;
revoke all on public.employee_equipment_assignments from anon, authenticated, public;
revoke all on public.employee_tool_allocations from anon, authenticated, public;
revoke all on public.employee_transfers from anon, authenticated, public;
revoke all on public.employee_transfer_items from anon, authenticated, public;
revoke all on public.panol_locations from anon, authenticated, public;

alter table public.companies force row level security;
alter table public.profiles force row level security;
alter table public.app_roles force row level security;
alter table public.tool_groups force row level security;
alter table public.tools force row level security;
alter table public.equipment_groups force row level security;
alter table public.equipments force row level security;
alter table public.equipment_custom_fields force row level security;
alter table public.equipment_custom_field_values force row level security;
alter table public.tool_custom_fields force row level security;
alter table public.tool_custom_field_values force row level security;
alter table public.employee_companies force row level security;
alter table public.employees force row level security;
alter table public.employee_equipment_assignments force row level security;
alter table public.employee_tool_allocations force row level security;
alter table public.employee_transfers force row level security;
alter table public.employee_transfer_items force row level security;
alter table public.panol_locations force row level security;

grant select, insert, update, delete on public.companies to authenticated;
grant select, insert, update, delete on public.profiles to authenticated;
grant select, insert, update, delete on public.app_roles to authenticated;
grant select, insert, update, delete on public.tool_groups to authenticated;
grant select, insert, update, delete on public.tools to authenticated;
grant select, insert, update, delete on public.equipment_groups to authenticated;
grant select, insert, update, delete on public.equipments to authenticated;
grant select, insert, update, delete on public.equipment_custom_fields to authenticated;
grant select, insert, update, delete on public.equipment_custom_field_values to authenticated;
grant select, insert, update, delete on public.tool_custom_fields to authenticated;
grant select, insert, update, delete on public.tool_custom_field_values to authenticated;
grant select, insert, update, delete on public.employee_companies to authenticated;
grant select, insert, update, delete on public.employees to authenticated;
grant select, insert, update, delete on public.employee_equipment_assignments to authenticated;
grant select, insert, update, delete on public.employee_tool_allocations to authenticated;
grant select, insert, update, delete on public.employee_transfers to authenticated;
grant select, insert, update, delete on public.employee_transfer_items to authenticated;
grant select, insert, update, delete on public.panol_locations to authenticated;
